let state={users:[],posts:[],top:[],following:[]};let activeUser=1;const $=s=>document.querySelector(s);const colors=['#c9f36b','#b6ddd0','#ffd29d','#d8c5f2','#f2b8aa'];
const avatar=(u,size='')=>`<div class="avatar" style="background:${colors[(u?.id||0)%colors.length]};${size}">${(u?.name||'?')[0].toUpperCase()}</div>`;
const user=id=>state.users.find(u=>u.id===id)||{id,username:'desconhecido',name:'Usuário'};
function escapeHTML(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function formatTime(ts){const d=new Date(ts*1000),diff=(Date.now()-d)/1000;if(diff>0&&diff<86400)return diff<3600?`${Math.max(1,Math.floor(diff/60))} min`:`${Math.floor(diff/3600)} h`;return d.toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}
async function api(path,data){const opt=data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{};const r=await fetch(path,opt);const body=await r.json();if(!r.ok)throw Error(body.error);return body}
async function load(){state=await api(`/api/state?user=${activeUser}`);if(!state.users.some(u=>u.id===activeUser)&&state.users[0])activeUser=state.users[0].id;render()}
async function command(cmd,success='Operação concluída'){try{const r=await api('/api/command',{command:cmd,user:activeUser});state=r.state;toast(r.ok?success:translateError(r.output.join(' ')),!r.ok);render();return r}catch(e){toast(e.message,true)}}
function translateError(s){const map={USER_EXISTS:'Este perfil já existe',USER_NOT_FOUND:'Usuário não encontrado',POST_EXISTS:'Este post já existe',POST_NOT_FOUND:'Publicação não encontrada',ALREADY_FOLLOWING:'Você já segue esta pessoa',NOT_FOLLOWING:'Você ainda não segue esta pessoa',ALREADY_LIKED:'Você já curtiu esta publicação',CANNOT_FOLLOW_SELF:'Você não pode seguir a si mesmo'};const key=Object.keys(map).find(k=>s.includes(k));return key?map[key]:'Não foi possível concluir a operação'}
function render(){const current=user(activeUser);$('#active-user').innerHTML=state.users.map(u=>`<option value="${u.id}" ${u.id===activeUser?'selected':''}>@${escapeHTML(u.username)}</option>`).join('');$('#header-avatar').textContent=current.name[0]?.toUpperCase()||'?';document.querySelectorAll('.current-avatar').forEach(x=>x.textContent=current.name[0]?.toUpperCase()||'?');$('#stat-users').textContent=state.users.length;$('#stat-posts').textContent=state.posts.length;$('#stat-ops').textContent=state.operations;$('#post-count').textContent=`${state.posts.length} publicaç${state.posts.length===1?'ão':'ões'}`;renderFeed(state.posts);renderPeople();renderRanking()}
function renderFeed(posts){$('#feed').innerHTML=posts.length?posts.map((p,i)=>{const u=user(p.authorId);return `<article class="post" style="animation-delay:${i*.04}s"> <div class="post-head">${avatar(u)}<div class="post-author"><strong>${escapeHTML(u.name)}</strong><span>@${escapeHTML(u.username)} · ${formatTime(p.timestamp)}</span></div><span class="post-id">#${p.id}</span></div><p class="post-text">${escapeHTML(p.text)}</p><div class="post-actions"><button onclick="like(${p.id})">♡ ${p.likes}</button><button onclick="comments(${p.id})">◯ Comentar</button><button onclick="comments(${p.id},true)">↳ Ver conversa</button><button class="delete" onclick="removePost(${p.id})">×</button></div></article>`}).join(''):'<div class="empty">Ainda não há publicações por aqui.</div>'}
function renderPeople(){const others=state.users.filter(u=>u.id!==activeUser).slice(0,4);$('#people-list').innerHTML=others.map(u=>`<div class="person">${avatar(u,'width:36px;height:36px;border-radius:11px')}<div class="person-info"><strong>${escapeHTML(u.name)}</strong><span>@${escapeHTML(u.username)}</span></div><button class="${state.following.includes(u.id)?'following':''}" onclick="follow(${u.id})">${state.following.includes(u.id)?'Seguindo':'Seguir'}</button></div>`).join('')+`<div class="person"><div class="avatar" style="width:36px;height:36px;border-radius:11px">＋</div><div class="person-info"><strong>Adicionar pessoa</strong><span>Crie um novo perfil</span></div><button onclick="openUser()">Criar</button></div>`}
function renderRanking(){const medals=['01','02','03'];$('#ranking').innerHTML=state.top.slice(0,3).map((p,i)=>`<div class="rank"><span>${medals[i]}</span><span class="rank-text">${escapeHTML(p.text)}</span><span class="rank-likes">♡ ${p.likes}</span></div>`).join('')||'<div class="empty">Sem ranking</div>'}
window.like=id=>command(`LIKE ${activeUser} ${id}`,'Publicação curtida');window.follow=id=>command(`${state.following.includes(id)?'UNFOLLOW':'FOLLOW'} ${activeUser} ${id}`,state.following.includes(id)?'Você deixou de seguir':'Agora vocês estão conectados');window.removePost=id=>{if(confirm('Remover esta publicação?'))command(`REMOVE_POST ${id}`,'Publicação removida')};
window.comments=async(id,view=false)=>{if(view){const r=await command(`LIST_COMMENTS ${id}`,'Comentários carregados');const lines=(r?.output||[]).filter(x=>x.startsWith('COMMENT '));alert(lines.length?lines.map(x=>x.split(' ').slice(3).join(' ')).join('\n\n'):'Ainda não há comentários.');return}const text=prompt('Escreva seu comentário:');if(text)command(`COMMENT ${activeUser} ${id} ${Date.now()%1000000} ${text.replace(/[\n\r]/g,' ')}`,'Comentário publicado')};
function openPost(){if(!state.users.length)return toast('Crie um perfil primeiro',true);$('#post-modal').showModal();setTimeout(()=>$('#post-text').focus(),100)}window.openUser=()=>$('#user-modal').showModal();
$('#new-post').onclick=$('#composer-trigger').onclick=$('#quick-post').onclick=openPost;$('#post-text').oninput=e=>$('#char-count').textContent=`${e.target.value.length} / 279`;$('#publish').onclick=e=>{e.preventDefault();const text=$('#post-text').value.trim();if(!text)return;command(`ADD_POST ${Date.now()%1000000} ${activeUser} ${Math.floor(Date.now()/1000)} ${text.replace(/[\n\r]/g,' ')}`,'Publicação criada');$('#post-text').value='';$('#post-modal').close()};
$('#create-user').onclick=e=>{e.preventDefault();const name=$('#user-name').value.trim(),username=$('#username').value.trim().replace(/\s/g,'');if(!name||!username)return;const id=Math.max(0,...state.users.map(u=>u.id))+1;command(`ADD_USER ${id} ${username} ${name}`,'Perfil criado');$('#user-modal').close()};
$('#active-user').onchange=async e=>{activeUser=+e.target.value;await load()};$('#search').oninput=e=>{const q=e.target.value.toLowerCase();renderFeed(state.posts.filter(p=>p.text.toLowerCase().includes(q)||user(p.authorId).name.toLowerCase().includes(q)))};$('#reset').onclick=async()=>{if(confirm('Restaurar os dados da demonstração?')){const r=await api('/api/reset',{user:1});activeUser=1;state=r.state;render();toast('Demonstração restaurada')}};$('#notifications').onclick=async()=>{const r=await command(`GET_NOTIFICATIONS ${activeUser} 20`,'Notificações atualizadas');const lines=(r?.output||[]).filter(x=>x.startsWith('NOTIFICATION'));alert(lines.length?lines.map(x=>{const p=x.split(' ');return p[1]==='FOLLOW'?`@${user(+p[2]).username} começou a seguir você`:`@${user(+p[2]).username} ${p[1]==='LIKE'?'curtiu':'comentou em'} seu post #${p[3]}`}).join('\n'):'Você está em dia!')};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.view==='top')renderFeed(state.top);else if(b.dataset.view==='people'){$('#people-list').scrollIntoView({behavior:'smooth'});renderFeed(state.posts)}else renderFeed(state.posts)});$('#show-all').onclick=()=>toast(`${state.users.length} pessoas fazem parte da MiniRede`);function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className=error?'show error':'show';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.className='',2600)}load().catch(e=>toast(e.message,true));
